.. _physical_quantities:

*****************************
Accessing Physical Quantities
*****************************

In order to compute the synthetic spectrum, TARDIS must either be told
or must calculate many physical properties of the model. To understand and
test the code it can be important to look at these values. One
easy way to do this is to run TARDIS in an interactive mode and then
inspect the model properties.

### Runing in interactive Python session

In [1]:
# Download the atomic data
from tardis.io.atom_data.util import download_atom_data
download_atom_data('kurucz_cd23_chianti_H_He')

# Download the example configuration file
!curl -O https://raw.githubusercontent.com/tardis-sn/tardis/master/docs/tardis_example.yml

/usr/share/miniconda/envs/tardis/lib/python3.7/importlib/_bootstrap.py:219: QAWarning: pyne.data is not yet QA compliant.
  return f(*args, **kwds)

[tardis.io.atom_data.atom_web_download][INFO   ]  Downloading atomic data from https://media.githubusercontent.com/media/tardis-sn/tardis-refdata/master/atom_data/kurucz_cd23_chianti_H_He.h5 to /home/runner/Downloads/tardis-data/kurucz_cd23_chianti_H_He.h5 (atom_web_download.py:46)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100   980  100   980    0     0   5975      0 --:--:-- --:--:-- --:--:--  5975

In [2]:
from tardis import run_tardis

simulation = run_tardis('tardis_example.yml')

[tardis.plasma.standard_plasmas][INFO   ]  Reading Atomic Data from kurucz_cd23_chianti_H_He.h5 (standard_plasmas.py:91)

[tardis.io.atom_data.util][INFO   ]  Atom Data kurucz_cd23_chianti_H_He.h5 not found in local path. Exists in TARDIS Data repo /home/runner/Downloads/tardis-data/kurucz_cd23_chianti_H_He.h5 (util.py:34)

[tardis.io.atom_data.base][INFO   ]  Read Atom Data with UUID=6f7b09e887a311e7a06b246e96350010 and MD5=864f1753714343c41f99cb065710cace. (base.py:179)

[tardis.io.atom_data.base][INFO   ]  Non provided atomic data: synpp_refs, photoionization_data, yg_data, two_photon_data (base.py:183)

[tardis.simulation.base][INFO   ]  Starting iteration 1/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 7.94217e+42 erg / s Luminosity absorbed = 2.65853e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	             t_rad    next_t_rad         w    next_w
	Shell
	0      9926.501965  10140.644658  0.400392  0.507494
	5      9852.611678  10224.009714  0.211205  0.196867
	10     9779.813302  10148.778794  0.142695  0.116978
	15     9708.082813   9874.634222  0.104556  0.086895

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 9933.952 K -- next t_inner 10703.212 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 2/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.07105e+43 erg / s Luminosity absorbed = 3.57633e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      10140.644658  10821.384716  0.507494  0.524662
	5      10224.009714  10956.472449  0.196867  0.202658
	10     10148.778794  10799.242900  0.116978  0.124504
	15      9874.634222  10483.027319  0.086895  0.093258

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10703.212 K -- next t_inner 10673.712 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 3/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.07443e+43 erg / s Luminosity absorbed = 3.39125e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      10821.384716  11001.634918  0.524662  0.482556
	5      10956.472449  11179.454369  0.202658  0.188921
	10     10799.242900  10951.713112  0.124504  0.118165
	15     10483.027319  10589.476598  0.093258  0.089482

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10673.712 K -- next t_inner 10635.953 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 4/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.05830e+43 erg / s Luminosity absorbed = 3.35196e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11001.634918  11038.698133  0.482556  0.468754
	5      11179.454369  11231.114026  0.188921  0.182460
	10     10951.713112  11036.771406  0.118165  0.113342
	15     10589.476598  10659.853383  0.089482  0.086103

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10635.953 K -- next t_inner 10638.407 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 5/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.05459e+43 erg / s Luminosity absorbed = 3.39886e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 1/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11038.698133  11004.024490  0.468754  0.478795
	5      11231.114026  11285.177363  0.182460  0.178029
	10     11036.771406  11029.754125  0.113342  0.112938
	15     10659.853383  10716.294187  0.086103  0.083857

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10638.407 K -- next t_inner 10650.202 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 6/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.06097e+43 erg / s Luminosity absorbed = 3.39806e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 2/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11004.024490  11049.228732  0.478795  0.469740
	5      11285.177363  11218.728488  0.178029  0.185207
	10     11029.754125  11086.886472  0.112938  0.112082
	15     10716.294187  10665.940454  0.083857  0.085575

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10650.202 K -- next t_inner 10645.955 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 7/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.06083e+43 erg / s Luminosity absorbed = 3.38215e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 3/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11049.228732  11037.085037  0.469740  0.469517
	5      11218.728488  11303.814508  0.185207  0.177527
	10     11086.886472  11052.157105  0.112082  0.112025
	15     10665.940454  10653.978725  0.085575  0.085977

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10645.955 K -- next t_inner 10642.050 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 8/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.06165e+43 erg / s Luminosity absorbed = 3.34987e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 4/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11037.085037  11052.295325  0.469517  0.471751
	5      11303.814508  11374.755682  0.177527  0.175215
	10     11052.157105  11103.737908  0.112025  0.110658
	15     10653.978725  10715.360232  0.085977  0.084035

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10642.050 K -- next t_inner 10636.106 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 9/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.05206e+43 erg / s Luminosity absorbed = 3.41087e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 5/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11052.295325  11054.591787  0.471751  0.468692
	5      11374.755682  11459.610589  0.175215  0.169663
	10     11103.737908  11140.791754  0.110658  0.108734
	15     10715.360232  10760.164549  0.084035  0.082231

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10636.106 K -- next t_inner 10654.313 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 10/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.06974e+43 erg / s Luminosity absorbed = 3.33492e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11054.591787  11038.824130  0.468692  0.474547
	5      11459.610589  11369.200845  0.169663  0.177414
	10     11140.791754  11085.643189  0.108734  0.112387
	15     10760.164549  10622.890289  0.082231  0.087752

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10654.313 K -- next t_inner 10628.190 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 11/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.05298e+43 erg / s Luminosity absorbed = 3.36322e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 1/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11038.824130  11033.009303  0.474547  0.471654
	5      11369.200845  11194.361016  0.177414  0.183879
	10     11085.643189  11002.144957  0.112387  0.114285
	15     10622.890289  10633.713758  0.087752  0.085933

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10628.190 K -- next t_inner 10644.054 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 12/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.05551e+43 erg / s Luminosity absorbed = 3.41974e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11033.009303  11074.304190  0.471654  0.467343
	5      11194.361016  11342.026260  0.183879  0.175666
	10     11002.144957  11110.772200  0.114285  0.110074
	15     10633.713758  10785.376593  0.085933  0.082053

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10644.054 K -- next t_inner 10653.543 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 13/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.06177e+43 erg / s Luminosity absorbed = 3.40573e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 1/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11074.304190  11087.525575  0.467343  0.465658
	5      11342.026260  11281.498582  0.175666  0.180363
	10     11110.772200  11090.703318  0.110074  0.111388
	15     10785.376593  10756.107815  0.082053  0.084068

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10653.543 K -- next t_inner 10647.277 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 14/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.06263e+43 erg / s Luminosity absorbed = 3.36913e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 2/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11087.525575  11068.046309  0.465658  0.469328
	5      11281.498582  11275.907139  0.180363  0.182477
	10     11090.703318  11027.955393  0.111388  0.113397
	15     10756.107815  10675.837041  0.084068  0.085358

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10647.277 K -- next t_inner 10638.875 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 15/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.05283e+43 erg / s Luminosity absorbed = 3.41721e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 3/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11068.046309  10967.319695  0.469328  0.483949
	5      11275.907139  11284.218727  0.182477  0.180501
	10     11027.955393  11022.886564  0.113397  0.113405
	15     10675.837041  10656.719190  0.085358  0.085836

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10638.875 K -- next t_inner 10655.125 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 16/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.05910e+43 erg / s Luminosity absorbed = 3.44452e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 4/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      10967.319695  11042.347173  0.483949  0.472474
	5      11284.218727  11307.076261  0.180501  0.176762
	10     11022.886564  11044.390776  0.113405  0.112774
	15     10656.719190  10644.126115  0.085836  0.085801

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10655.125 K -- next t_inner 10655.561 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 17/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.06688e+43 erg / s Luminosity absorbed = 3.37181e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11042.347173  11061.104094  0.472474  0.468044
	5      11307.076261  11369.434921  0.176762  0.175430
	10     11044.390776  11108.666526  0.112774  0.110410
	15     10644.126115  10824.561558  0.085801  0.081598

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10655.561 K -- next t_inner 10636.536 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 18/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.05723e+43 erg / s Luminosity absorbed = 3.36547e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 1/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11061.104094  11069.193824  0.468044  0.463972
	5      11369.434921  11323.781974  0.175430  0.176916
	10     11108.666526  11030.940701  0.110410  0.113009
	15     10824.561558  10675.606609  0.081598  0.084790

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10636.536 K -- next t_inner 10641.692 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 19/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.05579e+43 erg / s Luminosity absorbed = 3.40488e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Iteration converged 2/4 consecutive times. (base.py:227)

[tardis.simulation.base][INFO   ]  Plasma stratification:
	              t_rad    next_t_rad         w    next_w
	Shell
	0      11069.193824  11069.330894  0.463972  0.465831
	5      11323.781974  11329.643567  0.176916  0.176729
	10     11030.940701  11071.529176  0.113009  0.111480
	15     10675.606609  10655.557942  0.084790  0.085342

 (base.py:433)

[tardis.simulation.base][INFO   ]  t_inner 10641.692 K -- next t_inner 10650.463 K (base.py:434)

[tardis.simulation.base][INFO   ]  Starting iteration 20/20 (base.py:323)

[py.warnings         ][WARNING]  /usr/share/miniconda/envs/tardis/lib/python3.7/site-packages/astropy/units/equivalencies.py:124: RuntimeWarning: divide by zero encountered in double_scalars
  (si.m, si.Hz, lambda x: _si.c.value / x),
 (warnings.py:110)

[tardis.simulation.base][INFO   ]  Luminosity emitted = 1.06078e+43 erg / s Luminosity absorbed = 3.40079e+42 erg / s Luminosity requested = 1.05928e+43 erg / s (base.py:438)

[tardis.simulation.base][INFO   ]  Simulation finished in 20 iterations and took 37.05 s (base.py:381)

If all goes well, the simulation should run as usual. Afterwards, the
information from the simulation will all exist in `Simulation` and
can be examined.
Some examples for useful/interesting quantities are
given below (but much more information is available: contact us via 
[tardis-sn-users](http://groups.google.com/forum/#!forum/tardis-sn-users) if you need
further help).

### Examples of finding physical quantities

For example, two of our important quantities are the parameters of the
radiation field model, $T_{\rm rad}$ and $W$. These exist as `numpy.ndarray`

Thus `simulation.plasma.t_rad` will give you a list of the $T_{\rm rad}$-values for the model zones in cgs units.

In [3]:
simulation.plasma.t_rad

array([11069.33089377, 11165.15751924, 11272.62783772, 11372.4522524 ,
       11332.02806881, 11329.6435672 , 11294.51865104, 11261.56893248,
       11241.47812926, 11148.97525325, 11071.52917648, 11004.68560208,
       10946.39979159, 10861.42744062, 10784.4789371 , 10655.55794227,
       10586.11909387, 10567.9967492 , 10435.71120389, 10305.7063164 ])

Similarly, the $W$-values can be accessed using `simulation.plasma.w`

In [4]:
simulation.plasma.w

array([0.46583111, 0.35821399, 0.28478501, 0.23131748, 0.20190424,
       0.17672918, 0.15768939, 0.14187896, 0.1281619 , 0.11908551,
       0.11148042, 0.10454478, 0.09806677, 0.09312254, 0.08822151,
       0.08534236, 0.08173657, 0.07726564, 0.07559528, 0.07395579])

Several important quantities that were setup when the model was defined by the configuration file are located in the `model` section of the simulation. For example, the inner and outer velocity boundaries of the zones in the model is given by `simulation.model.v_inner.cgs` and `simulation.model.v_outer.cgs` respectively. These exist as Astropy [Quantities](http://astropy.readthedocs.org/en/v0.2.1/_generated/astropy.units.quantity.Quantity.html).

In [5]:
simulation.model.v_inner.cgs

<Quantity [1.100e+09, 1.145e+09, 1.190e+09, 1.235e+09, 1.280e+09,
           1.325e+09, 1.370e+09, 1.415e+09, 1.460e+09, 1.505e+09,
           1.550e+09, 1.595e+09, 1.640e+09, 1.685e+09, 1.730e+09,
           1.775e+09, 1.820e+09, 1.865e+09, 1.910e+09, 1.955e+09] cm / s>

In [6]:
simulation.model.v_outer.cgs

<Quantity [1.145e+09, 1.190e+09, 1.235e+09, 1.280e+09, 1.325e+09,
           1.370e+09, 1.415e+09, 1.460e+09, 1.505e+09, 1.550e+09,
           1.595e+09, 1.640e+09, 1.685e+09, 1.730e+09, 1.775e+09,
           1.820e+09, 1.865e+09, 1.910e+09, 1.955e+09, 2.000e+09] cm / s>

The average density in the zones is given by `simulation.model.density.cgs`. These also exist as Astropy [Quantities](http://astropy.readthedocs.org/en/v0.2.1/_generated/astropy.units.quantity.Quantity.html).

In [7]:
simulation.model.density.cgs

<Quantity [7.54280360e-14, 5.72847501e-14, 4.39607422e-14, 3.40628743e-14,
           2.66313464e-14, 2.09959645e-14, 1.66828721e-14, 1.33531053e-14,
           1.07615377e-14, 8.72908485e-15, 7.12365156e-15, 5.84692095e-15,
           4.82509279e-15, 4.00232416e-15, 3.33603855e-15, 2.79354038e-15,
           2.34955043e-15, 1.98439683e-15, 1.68267689e-15, 1.43225980e-15] g / cm3>

Many other interesting quantities are stored in the `plasma`.
For example the calculated ion populations and level populations is given by `simulation.plasma.ion_number_density` and `simulation.plasma.level_number_density` respectively.

In [8]:
simulation.plasma.ion_number_density

                                     0             1             2  \
atomic_number ion_number
8             0           9.817541e+02  4.952192e+02  2.514676e+02
              1           5.392046e+08  4.093669e+08  3.139475e+08
              2           2.226602e+05  3.079859e+05  4.402008e+05
              3           2.645841e-08  7.972540e-08  2.585740e-07
              4           0.000000e+00  0.000000e+00  0.000000e+00
...                                ...           ...           ...
20            16          0.000000e+00  0.000000e+00  0.000000e+00
              17          0.000000e+00  0.000000e+00  0.000000e+00
              18          0.000000e+00  0.000000e+00  0.000000e+00
              19          0.000000e+00  0.000000e+00  0.000000e+00
              20          0.000000e+00  0.000000e+00  0.000000e+00

                                     3             4             5  \
atomic_number ion_number
8             0           1.318559e+02  8.523577e+01  5.320207e+01
              1           2.429934e+08  1.899227e+08  1.496264e+08
              2           6.091628e+05  5.329124e+05  5.275052e+05
              3           7.655780e-07  6.973306e-07  8.635538e-07
              4           0.000000e+00  0.000000e+00  0.000000e+00
...                                ...           ...           ...
20            16          0.000000e+00  0.000000e+00  0.000000e+00
              17          0.000000e+00  0.000000e+00  0.000000e+00
              18          0.000000e+00  0.000000e+00  0.000000e+00
              19          0.000000e+00  0.000000e+00  0.000000e+00
              20          0.000000e+00  0.000000e+00  0.000000e+00

                                     6             7             8  \
atomic_number ion_number
8             0           3.527606e+01  2.366975e+01  1.582107e+01
              1           1.188395e+08  9.507571e+07  7.657002e+07
              2           4.690734e+05  4.198082e+05  3.917586e+05
              3           8.070076e-07  7.611136e-07  7.934242e-07
              4           0.000000e+00  0.000000e+00  0.000000e+00
...                                ...           ...           ...
20            16          0.000000e+00  0.000000e+00  0.000000e+00
              17          0.000000e+00  0.000000e+00  0.000000e+00
              18          0.000000e+00  0.000000e+00  0.000000e+00
              19          0.000000e+00  0.000000e+00  0.000000e+00
              20          0.000000e+00  0.000000e+00  0.000000e+00

                                     9            10            11  \
atomic_number ion_number
8             0           1.185305e+01  8.815497e+00  6.540669e+00
              1           6.213943e+07  5.072480e+07  4.163973e+07
              2           2.871442e+05  2.204204e+05  1.748728e+05
              3           4.430639e-07  2.767649e-07  1.870047e-07
              4           0.000000e+00  0.000000e+00  0.000000e+00
...                                ...           ...           ...
20            16          0.000000e+00  0.000000e+00  0.000000e+00
              17          0.000000e+00  0.000000e+00  0.000000e+00
              18          0.000000e+00  0.000000e+00  0.000000e+00
              19          0.000000e+00  0.000000e+00  0.000000e+00
              20          0.000000e+00  0.000000e+00  0.000000e+00

                                    12            13            14  \
atomic_number ion_number
8             0           4.850194e+00  3.782471e+00  2.948439e+00
              1           3.436439e+07  2.851733e+07  2.377784e+07
              2           1.425520e+05  1.055346e+05  8.003898e+04
              3           1.346884e-07  7.544950e-08  4.473829e-08
              4           0.000000e+00  0.000000e+00  0.000000e+00
...                                ...           ...           ...
20            16          0.000000e+00  0.000000e+00  0.000000e+00
              17          0.000000e+00  0.000000e+00  0.000000e+00
              18          0.000000e+00  0.000000e+00  0.000000e+00
              19          0.000000e+00  0.000000e+00  0.000000e+00
              20          0.000000e+00  0.000000e+00  0.000000e+00

                                    15            16            17  \
atomic_number ion_number
8             0           2.514696e+00  1.980990e+00  1.454287e+00
              1           1.992820e+07  1.676439e+07  1.415556e+07
              2           4.996889e+04  3.855664e+04  3.597715e+04
              3           1.606762e-08  9.868697e-09  9.803360e-09
              4           0.000000e+00  0.000000e+00  0.000000e+00
...                                ...           ...           ...
20            16          0.000000e+00  0.000000e+00  0.000000e+00
              17          0.000000e+00  0.000000e+00  0.000000e+00
              18          0.000000e+00  0.000000e+00  0.000000e+00
              19          0.000000e+00  0.000000e+00  0.000000e+00
              20          0.000000e+00  0.000000e+00  0.000000e+00

                                    18            19
atomic_number ion_number
8             0           1.288493e+00  1.151839e+00
              1           1.201203e+07  1.022981e+07
              2           2.173746e+04  1.307832e+04
              3           3.199626e-09  1.029618e-09
              4           0.000000e+00  0.000000e+00
...                                ...           ...
20            16          0.000000e+00  0.000000e+00
              17          0.000000e+00  0.000000e+00
              18          0.000000e+00  0.000000e+00
              19          0.000000e+00  0.000000e+00
              20          0.000000e+00  0.000000e+00

[94 rows x 20 columns]

In [9]:
simulation.plasma.level_number_density

                                                0           1           2  \
atomic_number ion_number level_number
8             0          0             513.492299  258.671585  131.154368
                         1             301.822270  152.069720   77.118971
                         2              99.712889   50.243057   25.481864
                         3              65.284281   33.474270   17.306588
                         4               1.270591    0.664649    0.351282
...                                           ...         ...         ...
20            16         0               0.000000    0.000000    0.000000
              17         0               0.000000    0.000000    0.000000
              18         0               0.000000    0.000000    0.000000
              19         0               0.000000    0.000000    0.000000
              20         0               0.000000    0.000000    0.000000

                                               3          4          5  \
atomic_number ion_number level_number
8             0          0             68.674580  44.418418  27.725805
                         1             40.387920  26.120864  16.304473
                         2             13.346116   8.631325   5.387607
                         3              9.224554   5.923827   3.696062
                         4              0.191034   0.121690   0.075890
...                                          ...        ...        ...
20            16         0              0.000000   0.000000   0.000000
              17         0              0.000000   0.000000   0.000000
              18         0              0.000000   0.000000   0.000000
              19         0              0.000000   0.000000   0.000000
              20         0              0.000000   0.000000   0.000000

                                               6          7         8  \
atomic_number ion_number level_number
8             0          0             18.392821  12.346995  8.255151
                         1             10.815431   7.259908  4.853770
                         2              3.573725   2.398818  1.603757
                         3              2.436586   1.626021  1.083219
                         4              0.049677   0.032930  0.021848
...                                          ...        ...       ...
20            16         0              0.000000   0.000000  0.000000
              17         0              0.000000   0.000000  0.000000
              18         0              0.000000   0.000000  0.000000
              19         0              0.000000   0.000000  0.000000
              20         0              0.000000   0.000000  0.000000

                                              9        10        11        12  \
atomic_number ion_number level_number
8             0          0             6.192690  4.610677  3.424086  2.541173
                         1             3.640496  2.710091  2.012378  1.493315
                         2             1.202786  0.895333  0.664793  0.493296
                         3             0.799011  0.586431  0.430088  0.315682
                         4             0.015812  0.011419  0.008257  0.005985
...                                         ...       ...       ...       ...
20            16         0             0.000000  0.000000  0.000000  0.000000
              17         0             0.000000  0.000000  0.000000  0.000000
              18         0             0.000000  0.000000  0.000000  0.000000
              19         0             0.000000  0.000000  0.000000  0.000000
              20         0             0.000000  0.000000  0.000000  0.000000

                                             13        14        15        16  \
atomic_number ion_number level_number
8             0          0             1.984107  1.548271  1.322879  1.043126
                         1             1.165766  0.909554  0.776946  0.612557
                         2             0.385068  0.300418  0.256590  0.202288
                         3             0.242490  0.186407  0.155243  0.120705
                         4             0.004514  0.003411  0.002760  0.002112
...                                         ...       ...       ...       ...
20            16         0             0.000000  0.000000  0.000000  0.000000
              17         0             0.000000  0.000000  0.000000  0.000000
              18         0             0.000000  0.000000  0.000000  0.000000
              19         0             0.000000  0.000000  0.000000  0.000000
              20         0             0.000000  0.000000  0.000000  0.000000

                                             17        18        19
atomic_number ion_number level_number
8             0          0             0.765974  0.679901  0.608892
                         1             0.449788  0.399136  0.357352
                         2             0.148533  0.131791  0.117980
                         3             0.088307  0.076267  0.066442
                         4             0.001539  0.001289  0.001088
...                                         ...       ...       ...
20            16         0             0.000000  0.000000  0.000000
              17         0             0.000000  0.000000  0.000000
              18         0             0.000000  0.000000  0.000000
              19         0             0.000000  0.000000  0.000000
              20         0             0.000000  0.000000  0.000000

[4435 rows x 20 columns]

These are stored as Pandas `DataFrames`. An index can be supplied to obtain the population in a particular zone. E.g., for the ion populations of the innermost zone (index = 0), we will use 
`simulation.plasma.ion_number_density[0]`

In [10]:
simulation.plasma.ion_number_density[0]

atomic_number  ion_number
8              0             9.817541e+02
               1             5.392046e+08
               2             2.226602e+05
               3             2.645841e-08
               4             0.000000e+00
                                 ...
20             16            0.000000e+00
               17            0.000000e+00
               18            0.000000e+00
               19            0.000000e+00
               20            0.000000e+00
Name: 0, Length: 94, dtype: float64

Ion populations for a particular ionization stage of a particular element can be accessed by specifying an appropriate tuple (𝑍,𝐶), which identifies the element (via atomic number 𝑍 ) and the charge (via the ion charge 𝐶 ). Thus, `simulation.plasma.ion_number_density.loc[14,1]` will identify the ion popuations for Si II (𝑍=14,𝐶=1) in all the zones.

In [11]:
simulation.plasma.ion_number_density.loc[14,1]

0     70833.163502
1     34861.243842
2     17211.393526
3      8779.777647
4      5721.865657
5      3563.344668
6      2378.033763
7      1604.932782
8      1074.816738
9       824.622359
10      625.499897
11      471.990280
12      355.146037
13      283.454849
14      225.652192
15      199.786180
16      160.473228
17      118.252827
18      108.994959
19      101.321273
Name: (14, 1), dtype: float64

The above examples can be combined to obtain e.g. the Si II population in the innermost zone
can be obtained by
`simulation.plasma.ion_number_density[0].loc[14,1]`

In [12]:
simulation.plasma.ion_number_density[0].loc[14,1]

70833.16350200417

The level populations are stored (and can be accessed) in a similar way - a third label can be used to pick out a particular atomic level. E.g., to pull out the population of the ground state (index 0) of Si II we can use `simulation.plasma.level_number_density.loc[14,1,0]`

In [13]:
simulation.plasma.level_number_density.loc[14,1,0]

0     23980.690090
1     11794.195085
2      5818.333741
3      2965.794314
4      1933.426172
5      1204.080564
6       803.766453
7       542.594090
8       363.426957
9       279.017554
10      211.760752
11      159.866349
12      120.339508
13       96.103679
14       76.546076
15       67.830067
16       54.507573
17       40.171395
18       37.057825
19       34.476854
Name: (14, 1, 0), dtype: float64

### Notes
- If you prefer to work in SI units, all the Astropy Quantities may instead by accessed with “xxx.si”.

- Information that is not stored as Astropy Quantities (e.g. the ion and level populations used in the example above) are usually stored in cgs units (i.e. cm−3 for the populations).